"""
API Router for Sentiment Alerts.

Provides endpoints for retrieving and managing high-risk stock alerts 
generated by the background monitoring system.
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from app.config.database import get_db
from app.domain.models import SentimentAlert

router = APIRouter()

@router.get("/alerts", tags=["Alerts"])
def get_alerts(db: Session = Depends(get_db)):
    """
    Fetches all high-risk sentiment alerts from the database, 
    ordered by most recent first.
    """
    alerts = db.query(SentimentAlert).order_by(SentimentAlert.timestamp.desc()).all()
    return alerts

@router.get("/alerts/unread", tags=["Alerts"])
def get_unread_alerts(db: Session = Depends(get_db)):
    """
    Fetches only unread high-risk sentiment alerts.
    Useful for displaying notifications to the user.
    """
    alerts = db.query(SentimentAlert).filter(SentimentAlert.is_read == 0).order_by(SentimentAlert.timestamp.desc()).all()
    return alerts

@router.post("/alerts/{alert_id}/read", tags=["Alerts"])
def mark_alert_read(alert_id: int, db: Session = Depends(get_db)):
    """
    Marks a specific alert as read (acknowledging the notification).
    """
    alert = db.query(SentimentAlert).filter(SentimentAlert.id == alert_id).first()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    
    alert.is_read = 1
    db.commit()
    return {"message": "Alert marked as read"}

